### ISSUE TITLE
Using time-based map/cache with expiring keys in ResourceServlet

### ISSUE THREAD

**Issue by ygpark80** [asual/lesscss-servlet#17]
I was just wondering.. wouldn't it be better to use some sort of time-based map/cache with expiring keys in your ResourceServlet implementation?

I think many of the users won't have any problems (esp memory issues) since they won't have tons of less files but..
I was looking at the sample code and saw a servlet mapping to *.jpg files. If a website has a lot of jpg files, wouldn't it be a problem?

**Comment by asual** [comment]
Your observation is absolutely correct. A proper implementation should not use a simple in-memory cache. I have used this servlet in the past for small images because I needed access to classpath resources. This capability is part of the Servlet 3.0 spec which is now available in all major containers. That said, this project should not be used for images and I'm going to remove the JPEG part from the docs.
